### ISSUE TITLE
high level roadmap

### ISSUE THREAD

**Issue by lucydot** [NU-CEM/singing-materials-app#1]
### Roadmap

- [ ] implement phonopy mesh file upload from user
- [ ]  import package for generating sound stream and/or audio file from phonon data (github.com/NU-CEM/singing-materials)
- [ ]  deploy on Microsoft Azure (?)
- [ ]  implement database to track requests to server, and the geographic origin (for our own monitoring)

### Related Links

- https://stackoverflow.com/questions/69933498/audio-not-playing-on-html-page-using-flask
- https://stackoverflow.com/questions/70092604/how-to-get-this-sounddv-py-file-to-run-inside-the-html-file-using-flask
- https://learn.microsoft.com/en-us/azure/app-service/quickstart-python?tabs=flask%2Cwindows%2Cazure-cli%2Cvscode-deploy%2Cdeploy-instructions-azportal%2Cterminal-bash%2Cdeploy-instructions-zip-azcli
- https://stackoverflow.com/questions/11620698/how-to-trigger-a-file-download-when-clicking-an-html-button-or-javascript
